### ISSUE TITLE
[Feature request] "Cel puțin o doză" graph

### ISSUE THREAD

**Issue by razvanra2** [code4romania/covid-19-date-la-zi#453]
I'd love to see a "Cel puțin o doză administrată" graph on the landing page

**Comment by catileptic** [comment]
Thank you for your suggestion!

Date la zi is a website that is part of Code for Romania's Covid-19 ecosystem of apps. These apps are developed in direct partnership with the government and the content that we publish on these apps comes directly from the official sources within institutions that communicate on the subject of the pandemic. We do not have the full agency to add to the types of graphs in Date la zi - each change needs to be agreed on inside the partnership. We are currently discussing an extensive list of new content, but we have not gotten the green light yet. 

I am closing this issue, but feel free to re-open this in order to continue discussing this issue.
